# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-27 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(null=True)),
                ('client', models.CharField(max_length=16, null=True)),
                ('fraction', models.IntegerField(null=True)),
            ],
        ),
    ]
